import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Footer } from '../components/Footer'
import { Links } from '../components/Links'
import { Headline } from '../components/Headline'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline title="About Page" emoji="😆" />

        <Links T1="😆" T2="😢" T3="🎅" T4="😢" />
      </main>

      <Footer />
    </div>
  )
}
