import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Footer } from "../components/Footer"
import { Links } from '../components/Links'
import { Headline } from '../components/Headline'
import { Main } from '../components/Main'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main
        title="Index Page" emoji="💩" code={<code className={styles.code}>pages/index.js</code>} onClick={() => alert("クリックされた")}

      />

      <Footer
        name="大山さん"
      />

    </div >
  )
}
